services:
  mysql-8:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "orders"
    ports:
      - "3306:3306"